application: awardr
version: 1
runtime: python
api_version: 1

#default_expiration: '3650d'

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /property/starwood/(.*)
  script: app/parsers.py
  login: admin
 
- url: /cron/(.*)
  script: app/cron.py
  login: admin
  
- url: /tasks/(.*)
  script: app/tasks.py
  login: admin
  
- url: /services/(.*)
  script: app/services.py

- url: /bulk/(.*)
  script: app/bulk.python
  
- url: /static2
  static_dir: static

- url: /rate-lookup
  script: app/views.py
  
- url: /
  script: app/views.py

- url: /(.*)
  script: app/views.py
  login: admin  

- url: /(.*)
  script: app/views.py
  login: admin