application: awardr
version: 1
runtime: python
api_version: 1

default_expiration: '3650d'

handlers:
- url: /property/starwood/(.*)
  script: app/parsers.py
  login: admin
 
- url: /cron/(.*)
  script: app/cron.py
  login: admin
  
- url: /tasks/(.*)
  script: app/tasks.py
  login: admin
  
- url: /services/(.*)
  script: app/services.py

- url: /b/(.*)
  script: app/bulk.python
  
- url: /static
  static_dir: static

- url: /(.*)
  script: app/views.py
  login: admin