application: awardr
version: 1
runtime: python
api_version: 1

#default_expiration: '3650d'

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /property/starwood/(.*)
  script: app/parsers.py
  login: admin
 
- url: /cron/(.*)
  script: app/cron.py
  login: admin
  
- url: /tasks/(.*)
  script: app/tasks.py
  login: admin
  
- url: /services/(.*)
  script: app/services.py
  
- url: /sandbox/(.*)
  script: app/sandbox.py

- url: /bulk/(.*)
  script: app/bulk.python
  
- url: /shell(|/(.*))
  script: app/shell.py
  login: admin
  
- url: /stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py
  
- url: /static2
  static_dir: static
  
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /robots.txt
  static_files: static/site/robots.txt
  upload: static/site/robots.txt

- url: /rate-lookup
  script: app/views.py
  
- url: /
  script: app/views.py

- url: /(.*)
  script: app/views.py

- url: /(.*)
  script: app/views.py
  login: admin
  

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^(.*/)?.*\.csv$
- ^(.*/)?.*\.sh$

  
admin_console:
  pages:
  - name: Shell
    url: /shell