application: awardr
version: 1
runtime: python
api_version: 1

default_expiration: '3650d'

handlers:
- url: /property/starwood/(.*)
  script: app/parsers.py
  
- url: /cron/property
  script: app/cron.py
  login: admin
  
- url: /tasks/(.*)
  script: app/tasks.py
  login: admin
  
- url: /
  script: app/views.py