# All the resources go here.

CATEGORY_AWARD_CHOICES = {
	'cash_points': {
		1: {'points': 1200, 'cash': 25,},
		2: {'points': 1600, 'cash': 30,},
		3: {'points': 2800, 'cash': 45,},
		4: {'points': 4000, 'cash': 60,},
		5: {'points': 4800, 'cash': 90,},
		6: {'points': 8000, 'cash': 150,},
	},

	# {category: [weekday, weekend]}
	'points': {
		1: [{'min': 3000, 'max': 3000}, {'min': 2000, 'max': 2000}],
		2: [{'min': 4000, 'max': 4000}, {'min': 3000, 'max': 3000}],
		3: [{'min': 7000, 'max': 7000}, {'min': 7000, 'max': 7000}],
		4: [{'min': 10000, 'max': 10000}, {'min': 10000, 'max': 10000}],
		5: [{'min': 12000, 'max': 16000}, {'min': 12000, 'max': 16000}],
		6: [{'min': 20000, 'max': 25000}, {'min': 20000, 'max': 25000}],
		7: [{'min': 30000, 'max': 35000}, {'min': 30000, 'max': 35000}],
	},
}

CURRENCIES = {
	'Albania': 'EUR',
	'Algeria': 'DZD',
	'Argentina': '',
	'Aruba': '',
	'Australia': '',
	'Austria': '',
	'Bahamas': '',
	'Bahrain': '',
	'Bangladesh': '',
	'Belgium': '',
	'Brazil': '',
	'Bulgaria': '',
	'Cambodia': '',
	'Cameroon': '',
	'Canada': '',
	'Cayman Islands': '',
	'Chad': '',
	'Chile': '',
	'China': '',
	'Colombia': '',
	'Croatia': '',
	'Czech Republic': '',
	'Djibouti': '',
	'Ecuador': '',
	'Egypt': '',
	'El Salvador': '',
	'Ethiopia': '',
	'Fiji': 'FJD',
	'Finland': '',
	'France': '',
	'French Polynesia': '',
	'Gabon': '',
	'Gambia': '',
	'Georgia, Republic of': '',
	'Germany': '',
	'Greece': '',
	'Guatemala': '',
	'Hungary': '',
	'India': '',
	'Indonesia': '',
	'Ireland': 'EUR',
	'Israel': '',
	'Italy': 'EUR',
	'Japan': 'JPY',
	'Jordan': 'JOD',
	'Kuwait': 'KWD',
	'Lebanon': '',
	'Lithuania': '',
	'Malaysia': '',
	'Maldives, Republic of': '',
	'Malta': '',
	'Mauritius': '',
	'Mexico': '',
	'Morocco': '',
	'Netherlands': '',
	'New Caledonia': '',
	'New Zealand': '',
	'Nigeria': '',
	'Pakistan': 'USD',
	'Panama, Republic of': '',
	'Paraguay': '',
	'Peru': '',
	'Poland': '',
	'Portugal': '',
	'Qatar': '',
	'Russia': 'RUB',
	'Saudi Arabia': '',
	'Senegal': '',
	'Seychelles': '',
	'Singapore': '',
	'Slovakia': '',
	'South Africa': 'ZAR',
	'South Korea': 'KRW',
	'Spain': '',
	'St. Maarten': 'USD',
	'Sweden': 'SEK',
	'Switzerland': 'CHF',
	'Syria': 'EUR',
	'Taiwan': 'TWD',
	'Thailand': 'THB',
	'Tunisia': 'TND',
	'Turkey': 'EUR',
	'Uganda': '',
	'United Arab Emirates': 'AED',
	'United Kingdom': 'GBP',
	'United States': 'USD',
	'Uruguay': 'USD',
	'Vietnam': 'VND',
	'Yemen': 'USD',
}